create table if not exists roles (
    id bigint generated by default as identity primary key,
    name varchar(50) not null unique,
    description varchar(255)
);

create table if not exists users (
    id bigint generated by default as identity primary key,
    name varchar(120) not null,
    username varchar(120) not null unique,
    password varchar(120) not null,
    role_id bigint not null,
    constraint fk_users_role foreign key (role_id) references roles (id)
);

create table if not exists permissions (
    id bigint generated by default as identity primary key,
    code varchar(80) not null unique,
    description varchar(255)
);

create table if not exists role_permissions (
    role_id bigint not null,
    permission_id bigint not null,
    primary key (role_id, permission_id),
    constraint fk_role_permissions_role foreign key (role_id) references roles (id),
    constraint fk_role_permissions_permission foreign key (permission_id) references permissions (id)
);

create table if not exists auth_tokens (
    id uuid primary key,
    user_id bigint not null,
    access_token varchar(1000) not null,
    refresh_token varchar(1000) not null,
    access_jti varchar(80) not null unique,
    refresh_jti varchar(80) not null unique,
    session_id varchar(80) not null,
    issued_at timestamp not null,
    access_expires_at timestamp not null,
    refresh_expires_at timestamp not null,
    revoked_at timestamp,
    replaced_by_token_id uuid,
    created_ip varchar(120),
    created_user_agent varchar(255),
    constraint fk_auth_tokens_user foreign key (user_id) references users (id),
    constraint fk_auth_tokens_replaced_by foreign key (replaced_by_token_id) references auth_tokens (id)
);

create index if not exists idx_auth_tokens_user_id on auth_tokens (user_id);
create index if not exists idx_auth_tokens_session_id on auth_tokens (session_id);

insert into roles (name, description)
select 'ADMIN', 'System administrator'
where not exists (select 1 from roles where name = 'ADMIN');

insert into roles (name, description)
select 'PROFESSOR', 'Professor'
where not exists (select 1 from roles where name = 'PROFESSOR');

insert into roles (name, description)
select 'STUDENT', 'Student'
where not exists (select 1 from roles where name = 'STUDENT');

insert into permissions (code, description)
select 'permissions.manage', 'Manage role permissions'
where not exists (select 1 from permissions where code = 'permissions.manage');
insert into permissions (code, description)
select 'users.read.any', 'Read any user profile'
where not exists (select 1 from permissions where code = 'users.read.any');
insert into permissions (code, description)
select 'users.read.self', 'Read own profile'
where not exists (select 1 from permissions where code = 'users.read.self');
insert into permissions (code, description)
select 'users.update.self', 'Update own profile'
where not exists (select 1 from permissions where code = 'users.update.self');
insert into permissions (code, description)
select 'users.create.professor', 'Create professor users'
where not exists (select 1 from permissions where code = 'users.create.professor');
insert into permissions (code, description)
select 'exams.create', 'Create exams'
where not exists (select 1 from permissions where code = 'exams.create');
insert into permissions (code, description)
select 'exams.solve', 'Solve exams'
where not exists (select 1 from permissions where code = 'exams.solve');
insert into permissions (code, description)
select 'exams.grade', 'Grade exams'
where not exists (select 1 from permissions where code = 'exams.grade');
insert into permissions (code, description)
select 'exam.validations.read.self', 'Read own validation comments'
where not exists (select 1 from permissions where code = 'exam.validations.read.self');
insert into permissions (code, description)
select 'exam.results.read.self', 'Read own exam results'
where not exists (select 1 from permissions where code = 'exam.results.read.self');

insert into role_permissions (role_id, permission_id)
select r.id, p.id from roles r join permissions p on p.code = 'permissions.manage'
where r.name = 'ADMIN'
and not exists (select 1 from role_permissions rp where rp.role_id = r.id and rp.permission_id = p.id);
insert into role_permissions (role_id, permission_id)
select r.id, p.id from roles r join permissions p on p.code = 'users.read.any'
where r.name = 'ADMIN'
and not exists (select 1 from role_permissions rp where rp.role_id = r.id and rp.permission_id = p.id);
insert into role_permissions (role_id, permission_id)
select r.id, p.id from roles r join permissions p on p.code = 'users.read.self'
where r.name in ('ADMIN', 'PROFESSOR', 'STUDENT')
and not exists (select 1 from role_permissions rp where rp.role_id = r.id and rp.permission_id = p.id);
insert into role_permissions (role_id, permission_id)
select r.id, p.id from roles r join permissions p on p.code = 'users.update.self'
where r.name in ('ADMIN', 'PROFESSOR', 'STUDENT')
and not exists (select 1 from role_permissions rp where rp.role_id = r.id and rp.permission_id = p.id);
insert into role_permissions (role_id, permission_id)
select r.id, p.id from roles r join permissions p on p.code = 'users.create.professor'
where r.name = 'ADMIN'
and not exists (select 1 from role_permissions rp where rp.role_id = r.id and rp.permission_id = p.id);
insert into role_permissions (role_id, permission_id)
select r.id, p.id from roles r join permissions p on p.code = 'exams.create'
where r.name in ('ADMIN', 'PROFESSOR')
and not exists (select 1 from role_permissions rp where rp.role_id = r.id and rp.permission_id = p.id);
insert into role_permissions (role_id, permission_id)
select r.id, p.id from roles r join permissions p on p.code = 'exams.solve'
where r.name in ('ADMIN', 'STUDENT')
and not exists (select 1 from role_permissions rp where rp.role_id = r.id and rp.permission_id = p.id);
insert into role_permissions (role_id, permission_id)
select r.id, p.id from roles r join permissions p on p.code = 'exams.grade'
where r.name in ('ADMIN', 'PROFESSOR')
and not exists (select 1 from role_permissions rp where rp.role_id = r.id and rp.permission_id = p.id);
insert into role_permissions (role_id, permission_id)
select r.id, p.id from roles r join permissions p on p.code = 'exam.validations.read.self'
where r.name = 'STUDENT'
and not exists (select 1 from role_permissions rp where rp.role_id = r.id and rp.permission_id = p.id);
insert into role_permissions (role_id, permission_id)
select r.id, p.id from roles r join permissions p on p.code = 'exam.results.read.self'
where r.name = 'STUDENT'
and not exists (select 1 from role_permissions rp where rp.role_id = r.id and rp.permission_id = p.id);
