create table if not exists exams (
    id bigint generated by default as identity primary key,
    title varchar(255) not null,
    description varchar(255),
    duration_minutes integer not null,
    professor_id bigint not null,
    constraint fk_exams_professor foreign key (professor_id) references users (id)
);

create table if not exists exam_calls (
    id bigint generated by default as identity primary key,
    exam_id bigint,
    start_date timestamp,
    end_date timestamp,
    total_capacity integer,
    current_enrollment integer,
    constraint fk_exam_calls_exam foreign key (exam_id) references exams (id)
);

create table if not exists questions (
    id bigint generated by default as identity primary key,
    exam_id bigint not null,
    statement text,
    type varchar(30),
    points integer,
    constraint fk_questions_exam foreign key (exam_id) references exams (id)
);

create table if not exists exam_attempts (
    id bigint generated by default as identity primary key,
    exam_call_id bigint not null,
    student_id bigint not null,
    started_at timestamp,
    submitted_at timestamp,
    status varchar(30) not null,
    final_score decimal(38,2),
    constraint fk_exam_attempts_exam_call foreign key (exam_call_id) references exam_calls (id),
    constraint fk_exam_attempts_student foreign key (student_id) references users (id),
    constraint uk_exam_attempt_call_student unique (exam_call_id, student_id)
);

create table if not exists attempt_questions (
    id bigint generated by default as identity primary key,
    attempt_id bigint not null,
    question_id bigint not null,
    question_order integer,
    answer_text text,
    awarded_score decimal(38,2),
    review_comment text,
    constraint fk_attempt_questions_attempt foreign key (attempt_id) references exam_attempts (id),
    constraint fk_attempt_questions_question foreign key (question_id) references questions (id)
);
