spring:
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
  datasource:
    url: jdbc:h2:mem:examdb;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password: ""
  flyway:
    enabled: true
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

app:
  cors:
    allowed-origins:
      - http://localhost:4200
  jwt:
    issuer: exam-system
    secret: ${APP_JWT_SECRET:VGhpc0lzQURldk9ubHlTZWNyZXRLZXlGb3JKV1QzMl9CeXRlc19NaW5pbXVtISE=}
    access-ttl: 15m
    refresh-ttl: 7d
  bootstrap:
    seed-admin: true
    seed-local-test-users: true
    admin-username: admin
    admin-password: admin123
    admin-name: System Admin
    professor-username: profesor
    professor-password: profesor123
    professor-name: Usuario Profesor
    student-username: estudiante
    student-password: estudiante123
    student-name: Usuario Estudiante
